ECommerce/Controllers/ActorsController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers;

public class ActorsController : Controller
{
    private readonly IActorsService _service;

    public ActorsController(IActorsService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allActors = await _service.GetAllAsync();
        return View(allActors);     
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }
   
    [HttpPost]
    public async Task<IActionResult> Create(Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }

        await _service.AddAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Detail(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }


    public async Task<IActionResult> Edit(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }

        await _service.UpdateAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost,ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int Id)
    { 
        await _service.DeleteAsync(Id);
        return RedirectToAction(nameof(Index));
    }
}

ECommerce/Controllers/CinemasController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers;

public class CinemasController : Controller
{
    private readonly ICinemasService _service;

    public CinemasController(ICinemasService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allCinemas = await _service.GetAllAsync();
        return View(allCinemas);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Cinema cinema)
    {
        if (!ModelState.IsValid)
        {
            return View(cinema);
        }

        await _service.AddAsync(cinema);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Detail(int id)
    {
        var cinemaDetail = await _service.GetByIdAsync(id);
        if (cinemaDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(cinemaDetail);
    }


    public async Task<IActionResult> Edit(int id)
    {
        var cinemaDetail = await _service.GetByIdAsync(id);
        if (cinemaDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(cinemaDetail);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Cinema cinema)
    {
        if (!ModelState.IsValid)
        {
            return View(cinema);
        }

        await _service.UpdateAsync(cinema);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int Id)
    {
        await _service.DeleteAsync(Id);
        return RedirectToAction(nameof(Index));
    }
}

ECommerce/Controllers/MoviesController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECommerce.Controllers;

public class MoviesController : Controller
{
    readonly IMoviesService _service;

    public MoviesController(IMoviesService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allMovies = await _service.GetAllAsync(m => m.Cinema);
        return View(allMovies);
    }


    public async Task<IActionResult> Details(int id)
    {
        var movieDetail = await _service.GetMovieByIdAsync(id);
        return View(movieDetail);
    }

    public async Task<IActionResult> Create()
    {
        var movieDropdowns = await _service.GetMovieDropdownsValuesAsync();

        ViewBag.Cinemas = new SelectList(movieDropdowns.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdowns.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdowns.Actors, "Id", "FullName");

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(MovieVM movie)
    {
        if (!ModelState.IsValid)
        {
            return View(movie);
        }

        await _service.AddMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> Edit(int id)
    {
        var existingMovie = await _service.GetMovieByIdAsync(id);
        if (existingMovie is null) return View("_NotFound");

        var response = new MovieVM()
        {
            Id = existingMovie.Id,
            Description = existingMovie.Description,
            ImageUrl = existingMovie.ImageUrl,
            EndDate = existingMovie.EndDate,
            MovieCategory = existingMovie.MovieCategory,
            Name = existingMovie.Name,
            Price = existingMovie.Price,
            CinemaId = existingMovie.CinemaId,
            ProducerId = existingMovie.ProducerId,
            StartDate = existingMovie.StartDate,
            ActorIds = existingMovie.Actors_Movies.Select(a => a.ActorId).ToList()
        };

        var movieDropdowns = await _service.GetMovieDropdownsValuesAsync();

        ViewBag.Cinemas = new SelectList(movieDropdowns.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdowns.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdowns.Actors, "Id", "FullName");

        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(MovieVM movie)
    {
        if (movie.Id == 0)
        {
            return View("_NotFound");
        }

        if (!ModelState.IsValid)
        {
            return View(movie);
        }

        await _service.UpdateMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Filter(string searchString)
    {
        var allMovies = await _service.GetAllAsync(m => m.Cinema);

        if (!string.IsNullOrEmpty(searchString.ToLower()))
        {
            var filteredResult = allMovies.Where(m => m.Name.ToLower().Contains(searchString)
                                                 || m.Description.ToLower().Contains(searchString))
                                                 .ToList();
            if (filteredResult.Any())
            {
                return View("Index", filteredResult);
            }
            else
            {
                return View("Index", allMovies);
            }
        }
        return View("Index", allMovies);
    }
}

ECommerce/Controllers/OrdersController.cs
using ECommerce.Data.Cart;
using ECommerce.Data.Services;
using ECommerce.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IOrdersService _ordersService;
        private readonly ShoppingCart _shoppingCart;

        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            int userId = 1;
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item is not null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item is not null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            int userId = 1;
            string email = "";

            await _ordersService.StoreOrderAsync(items, userId, email);

            await _shoppingCart.ClearShoppingCartAsync();
            return View(items);

        }
    }
}

ECommerce/Views/Shared/_CreateItem.cshtml
@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
{

    <div style="position: fixed; right:25px; bottom:25px" class="text-white">
        <a asp-controller=@Model asp-action="create" class="btn btn-success">
            <i class="bi bi-circle">Yeni Ekle</i>
        </a>
    </div>
}

ECommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ETicaret</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerce.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    ,
</head>
<body>
    <header style="margin-top:-20px;">
        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">E-Film</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index">
                                <i class="badge-info bi-film"></i>
                                Filmler
                            </a>
                        </li>

                        @if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Yönetim
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index">
                                        <i class="bi bi-camera-reels"></i> Sinemalar
                                    </a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index">
                                        <i class="bi bi-headset"></i> Prodüktörler
                                    </a>
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index">
                                        <i class="bi bi-person-square"></i> Aktörler
                                    </a>
                                </div>
                            </li>
                        }
                    </ul>
                    <form class="form-inline my-1 my-lg-0" style="padding-right:15px;" asp-controller="Movies" asp-action="Filter">
                        <input name="searchString" type="text" class="form-control d-inline w-75" placeholder="Bir film arayın..." />
                        <button class="btn btn-outline-success" type="submit">
                            <i class="bi bi-search"></i>
                        </button>
                    </form>

                    <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartSummary")
                    </ul>

                    <partial name="_identity.cshtml" />

                </div>
            </div>
        </nav>

    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - E-Film
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ECommerce/Views/Shared/_NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info text-center">Aradığınız kayda ulaşılamıyor.</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="movies" asp-action="index">Ana Sayfa</a>
    </div>
</div>

ECommerce/Views/Shared/_identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0"
       asp-controller="Accounts" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i>
        Giriş Yap
    </a>
    <span style="padding:5px;"></span>
    <a class="btn btn-outline-success my-2 my-sm-0"
       asp-controller="Accounts" asp-action="Register">
        <i class="bi bi-person-plus"></i>
        Kayıt Ol
    </a>
    <span style="padding:5px;"></span>
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle"
                type="button" id="profile-btn" data-bs-toggle="dropdown"
                aria-expanded="false">
            <i class="bi bi-person-badge"></i>Merhaba @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Siparişlerim
                </a>
            </li>
        </ul>
    </div>

    <span style="padding:5px;"></span>
    <form asp-controller="Accounts" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i>Çıkış yap
        </button>
    </form>
}