ECommerce/Controllers/ActorsController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers;

public class ActorsController : Controller
{
    private readonly IActorsService _service;

    public ActorsController(IActorsService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allActors = await _service.GetAllAsync();
        return View(allActors);     
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }
   
    [HttpPost]
    public async Task<IActionResult> Create(Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }

        await _service.AddAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Detail(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }


    public async Task<IActionResult> Edit(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Actor actor)
    {
        if (!ModelState.IsValid)
        {
            return View(actor);
        }

        await _service.UpdateAsync(actor);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost,ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int Id)
    { 
        await _service.DeleteAsync(Id);
        return RedirectToAction(nameof(Index));
    }
}

ECommerce/Controllers/CinemasController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers;

public class CinemasController : Controller
{
    private readonly ICinemasService _service;

    public CinemasController(ICinemasService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allCinemas = await _service.GetAllAsync();
        return View(allCinemas);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Cinema cinema)
    {
        if (!ModelState.IsValid)
        {
            return View(cinema);
        }

        await _service.AddAsync(cinema);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Detail(int id)
    {
        var cinemaDetail = await _service.GetByIdAsync(id);
        if (cinemaDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(cinemaDetail);
    }


    public async Task<IActionResult> Edit(int id)
    {
        var cinemaDetail = await _service.GetByIdAsync(id);
        if (cinemaDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(cinemaDetail);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Cinema cinema)
    {
        if (!ModelState.IsValid)
        {
            return View(cinema);
        }

        await _service.UpdateAsync(cinema);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var actorDetail = await _service.GetByIdAsync(id);
        if (actorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(actorDetail);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int Id)
    {
        await _service.DeleteAsync(Id);
        return RedirectToAction(nameof(Index));
    }
}

ECommerce/Controllers/MoviesController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ECommerce.Controllers;

public class MoviesController : Controller
{
    readonly IMoviesService _service;

    public MoviesController(IMoviesService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allMovies = await _service.GetAllAsync(m => m.Cinema);
        return View(allMovies);
    }


    public async Task<IActionResult> Details(int id)
    {
        var movieDetail = await _service.GetMovieByIdAsync(id);
        return View(movieDetail);
    }

    public async Task<IActionResult> Create()
    {
        var movieDropdowns = await _service.GetMovieDropdownsValuesAsync();

        ViewBag.Cinemas = new SelectList(movieDropdowns.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdowns.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdowns.Actors, "Id", "FullName");

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(MovieVM movie)
    {
        if (!ModelState.IsValid)
        {
            return View(movie);
        }

        await _service.AddMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }


    public async Task<IActionResult> Edit(int id)
    {
        var existingMovie = await _service.GetMovieByIdAsync(id);
        if (existingMovie is null) return View("_NotFound");

        var response = new MovieVM()
        {
            Id = existingMovie.Id,
            Description = existingMovie.Description,
            ImageUrl = existingMovie.ImageUrl,
            EndDate = existingMovie.EndDate,
            MovieCategory = existingMovie.MovieCategory,
            Name = existingMovie.Name,
            Price = existingMovie.Price,
            CinemaId = existingMovie.CinemaId,
            ProducerId = existingMovie.ProducerId,
            StartDate = existingMovie.StartDate,
            ActorIds = existingMovie.Actors_Movies.Select(a => a.ActorId).ToList()
        };

        var movieDropdowns = await _service.GetMovieDropdownsValuesAsync();

        ViewBag.Cinemas = new SelectList(movieDropdowns.Cinemas, "Id", "Name");
        ViewBag.Producers = new SelectList(movieDropdowns.Producers, "Id", "FullName");
        ViewBag.Actors = new SelectList(movieDropdowns.Actors, "Id", "FullName");

        return View(response);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(MovieVM movie)
    {
        if (movie.Id == 0)
        {
            return View("_NotFound");
        }

        if (!ModelState.IsValid)
        {
            return View(movie);
        }

        await _service.UpdateMovieAsync(movie);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Filter(string searchString)
    {
        var allMovies = await _service.GetAllAsync(m => m.Cinema);

        if (!string.IsNullOrEmpty(searchString.ToLower()))
        {
            var filteredResult = allMovies.Where(m => m.Name.ToLower().Contains(searchString)
                                                 || m.Description.ToLower().Contains(searchString))
                                                 .ToList();
            if (filteredResult.Any())
            {
                return View("Index", filteredResult);
            }
            else
            {
                return View("Index", allMovies);
            }
        }
        return View("Index", allMovies);
    }
}

ECommerce/Controllers/OrdersController.cs
using ECommerce.Data.Cart;
using ECommerce.Data.Services;
using ECommerce.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers
{
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly IOrdersService _ordersService;
        private readonly ShoppingCart _shoppingCart;

        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            int userId = 1;
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item is not null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item is not null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            int userId = 1;
            string email = "";

            await _ordersService.StoreOrderAsync(items, userId, email);

            await _shoppingCart.ClearShoppingCartAsync();
            return View(items);

        }
    }
}

ECommerce/Controllers/ProducersController.cs
using ECommerce.Data.Services;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;

namespace ECommerce.Controllers;

public class ProducersController : Controller
{
    readonly IProducersService _service;

    public ProducersController(IProducersService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index()
    {
        var allProducers = await _service.GetAllAsync();
        return View(allProducers);
    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(Producer producer)
    {
        if (!ModelState.IsValid)
        {
            return View(producer);
        }

        await _service.AddAsync(producer);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Detail(int id)
    {
        var productorDetail = await _service.GetByIdAsync(id);
        if (productorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(productorDetail);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var productorDetail = await _service.GetByIdAsync(id);
        if (productorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(productorDetail);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Producer producer)
    {
        if (!ModelState.IsValid)
        {
            return View(producer);
        }

        await _service.UpdateAsync(producer);
        return RedirectToAction(nameof(Index));
    }

    public async Task<IActionResult> Delete(int id)
    {
        var productorDetail = await _service.GetByIdAsync(id);
        if (productorDetail.Id == 0)
        {
            return View("_NotFound");
        }

        return View(productorDetail);
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeleteConfirmed(int Id)
    {
        await _service.DeleteAsync(Id);
        return RedirectToAction(nameof(Index));
    }
}

ECommerce/Views/Movies/Create.cshtml
@using ECommerce.Data
@model MovieVM
@{
    ViewData["Title"] = "Yeni film kaydet";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Yeni film ekle</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()" ></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img style="width:250px;" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Kaydet" class="btn btn-outline-success float-lg-end"/>
                        <a class="btn btn-secondary" action="Index">Filmleri göster</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        });
    </script>
}

ECommerce/Views/Movies/Details.cshtml
@model Movie;
@{
    ViewData["Title"] = "Film Detayı";
}
<div class="row mt-4">

    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas"
                               asp-action="Detail"
                               asp-route-id=@Model.CinemaId>
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers"
                               asp-action="Detail"
                               asp-route-id=@Model.ProducerId>
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                <div class="column text-center">
                                    @foreach (var actor in Model.Actors_Movies)
                                    {
                                        <img class="border-info rounded-circle float-lg-start"
                                             src=@actor.Actor.ProfilePictureUrl
                                             style="max-width:150px;" />
                                        <a class="float-lg-start" asp-controller="Actors" asp-action="Detail" asp-route-id=@actor.Actor.Id>
                                            @actor.Actor.FullName
                                        </a>
                                    }
                                </div>
                            </div>
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer ">
                        <p class="card-text">
                            <a class="btn btn-outline-primary justify-content-end" asp-action="Index">
                                Back to list
                            </a>
                            <a class="btn btn-success text-white @((DateTime.Now > Model.EndDate) ? "disabled" : "")"
                               asp-controller="Orders"
                               asp-action="AddItemToShoppingCart"
                               asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

ECommerce/Views/Movies/Edit.cshtml
@using ECommerce.Data
@model MovieVM
@{
    ViewData["Title"] = "Film güncelle";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Film güncelle</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" multiple asp-items="ViewBag.Actors"></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img style="width:250px;" id="ImageUrlPreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Güncelle" class="btn btn-outline-success float-lg-end" />
                        <a class="btn btn-secondary" asp-action="Index">Filmleri göster</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageUrl").val();
        });


        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        });
    </script>
}

ECommerce/Views/Movies/Index.cshtml
@model IEnumerable<Movie>;
@{
    ViewData["Title"] = "Film Listesi";
}
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @if (User.Identity.IsAuthenticated 
                                    && User.IsInRole("admin"))
                                    {
                                        <a class="text-white d-flex justify-content-end"
                                           asp-action="Edit" asp-route-id="@item.Id">
                                            <i class="bi bi-pencil-square"></i>
                                            @item.Name
                                        </a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary justify-content-end" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>

                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                                   asp-controller="Orders"
                                   asp-action="AddItemToShoppingCart"
                                   asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>


@await Html.PartialAsync("_CreateItem", "Movies")